name: Deploy dist
on: [push,workflow_dispatch]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: <owner>/<repo>
          token: ${{ secrets.REPO_NAME }}